VERSION=v2.3.6

gomod:
	go get techtradechain.com/techtradechain/common/v2@v2.3.7
	go get techtradechain.com/techtradechain/pb-go/v2@v2.3.6
	go get techtradechain.com/techtradechain/logger/v2@v2.3.4
	go mod tidy
